// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/nodes": {
            "get": {
                "description": "返回 PVE 集群中所有节点列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "列出所有节点",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/nodes/{node}": {
            "get": {
                "description": "返回指定节点的详细状态信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "获取指定节点信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点名称",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/nodes/{node}/vms": {
            "get": {
                "description": "返回指定节点上所有 QEMU 虚拟机列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vms"
                ],
                "summary": "列出节点上所有虚拟机",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点名称",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "通过 PVE 创建新虚拟机，并在创建时通过 import-from 导入指定磁盘卷。\n支持可选的 CloudInit 配置（ciUser、ciPassword、sshKeys、ipConfig0、nameserver、searchDomain）；\n当请求体包含任意 CloudInit 字段时，系统自动附加 CloudInit 驱动盘（ide2）及对应配置。\nciPackages 非空时在 snippetsStorage 中生成 cloud-init user-data Snippet（自动执行 package_update/upgrade，并将 ciUser、ciPassword、sshKeys 写入 user-data）并通过 cicustom 引用（snippetsStorage 此时必填）。\n成功后响应 Location 头指向新虚拟机资源路径。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vms"
                ],
                "summary": "新建虚拟机并导入磁盘",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点名称",
                        "name": "node",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "创建参数（vmid、name、cores、memory、diskSource、storage 为必填；CloudInit 字段均为可选；ciPackages 非空时 snippetsStorage 必填）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pve.CreateVmRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/nodes/{node}/vms/{vmid}": {
            "get": {
                "description": "返回指定虚拟机的当前状态信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vms"
                ],
                "summary": "获取指定虚拟机信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点名称",
                        "name": "node",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "虚拟机 ID",
                        "name": "vmid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "异步删除指定虚拟机，返回 PVE 任务 ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vms"
                ],
                "summary": "删除虚拟机",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点名称",
                        "name": "node",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "虚拟机 ID",
                        "name": "vmid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/nodes/{node}/vms/{vmid}/start": {
            "post": {
                "description": "异步启动指定虚拟机，返回 PVE 任务 ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vms"
                ],
                "summary": "启动虚拟机",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点名称",
                        "name": "node",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "虚拟机 ID",
                        "name": "vmid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/nodes/{node}/vms/{vmid}/stop": {
            "post": {
                "description": "异步停止指定虚拟机，返回 PVE 任务 ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vms"
                ],
                "summary": "停止虚拟机",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点名称",
                        "name": "node",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "虚拟机 ID",
                        "name": "vmid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/storage": {
            "get": {
                "description": "返回 PVE 中所有存储资源列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "summary": "列出所有存储",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pve.CreateVmRequest": {
            "type": "object",
            "properties": {
                "aptMirror": {
                    "description": "APT 镜像源地址，写入 cloud-init apt.primary（可选，仅 ciPackages 非空时生效）",
                    "type": "string",
                    "example": "http://mirrors.aliyun.com/ubuntu"
                },
                "ciPackages": {
                    "description": "CloudInit 首次开机需安装的软件包列表（可选；非空时须同时指定 snippetsStorage）",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "qemu-guest-agent"
                    ]
                },
                "ciPassword": {
                    "description": "CloudInit 登录密码（可选）",
                    "type": "string",
                    "example": "secret"
                },
                "ciUser": {
                    "description": "CloudInit 配置（可选，使用云镜像时配置首次启动参数）",
                    "type": "string",
                    "example": "ubuntu"
                },
                "cores": {
                    "description": "CPU 核数（必填）",
                    "type": "integer",
                    "example": 2
                },
                "diskFormat": {
                    "description": "源磁盘格式，如 qcow2/raw（可选）",
                    "type": "string",
                    "example": "qcow2"
                },
                "diskInterface": {
                    "description": "磁盘接口类型，默认 virtio0（可选）",
                    "type": "string",
                    "example": "scsi0"
                },
                "diskSource": {
                    "description": "导入磁盘来源，格式 storage:path（必填）",
                    "type": "string",
                    "example": "local:import/noble-server-cloudimg-amd64.qcow2"
                },
                "ipConfig0": {
                    "description": "CloudInit 网络配置，格式同 PVE ipconfig0，如 ip=dhcp（可选）",
                    "type": "string",
                    "example": "ip=192.168.1.100/24,gw=192.168.1.1"
                },
                "memory": {
                    "description": "内存大小，单位 MB（必填）",
                    "type": "integer",
                    "example": 2048
                },
                "name": {
                    "description": "虚拟机名称（必填）",
                    "type": "string",
                    "example": "my-vm"
                },
                "nameserver": {
                    "description": "CloudInit DNS 服务器地址（可选）",
                    "type": "string",
                    "example": "8.8.8.8"
                },
                "network": {
                    "description": "网络设备配置，格式同 PVE net0，默认 virtio,bridge=vmbr0（可选）",
                    "type": "string",
                    "example": "virtio,bridge=vmbr0"
                },
                "searchDomain": {
                    "description": "CloudInit DNS 搜索域（可选）",
                    "type": "string",
                    "example": "example.com"
                },
                "snippetsStorage": {
                    "description": "存放 cloud-init user-data Snippet 的 PVE 存储名称（ciPackages 非空时必填）",
                    "type": "string",
                    "example": "local"
                },
                "sshKeys": {
                    "description": "CloudInit SSH 公钥，多个公钥用换行分隔（可选）",
                    "type": "string",
                    "example": "ssh-rsa AAAA..."
                },
                "storage": {
                    "description": "目标存储池（必填）",
                    "type": "string",
                    "example": "local-lvm"
                },
                "vmid": {
                    "description": "新虚拟机 VMID（必填）",
                    "type": "integer",
                    "example": 200
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/pve",
	Schemes:          []string{},
	Title:            "Hyperflow API",
	Description:      "Hyperflow PVE 管理接口",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
